"""auto-gen-vote

Revision ID: 241ce4f5182d
Revises: adfcbdb7a7c4
Create Date: 2022-12-09 20:49:24.341344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241ce4f5182d'
down_revision = 'adfcbdb7a7c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('post_id', sa.INTEGER(), nullable=False),
                    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    op.create_foreign_key("votes_users_fk", source_table="votes", referent_table="users",
                          local_cols=["user_id"], remote_cols=["id"], ondelete="CASCADE")
    op.create_foreign_key("votes_posts_fk", source_table="votes", referent_table="posts",
                          local_cols=["post_id"], remote_cols=["id"], ondelete="CASCADE")
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vote_users_fk", table_name="votes")
    op.drop_constraint("vote_post_fk", table_name="votes")
    op.drop_column('votes', 'user_id')
    op.drop_column('votes', 'post_id')
    op.drop_table('votes')
    # ### end Alembic commands ###
